from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
tag_prefix = "v"
branch_whitelist = [
    "main"
]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    "mvn versions:set -DnewVersion={{version}}"
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
    "git push origin --tags",
    "mvn versions:set -DnewVersion={{version|1.0.0+minor-SNAPSHOT}}",
    "git add pom.xml",
    "cog commit chore \"bump snapshot to {{version|1.0.0+1minor-SNAPSHOT}} [skip ci]\"",
    "git push",
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
